name: Run Tests

on:
  push:
    branches:
      - main  # Запускать только для пушей в ветку 'main'
  pull_request:
    branches:
      - main  # Запускать на PR в ветку 'main'

jobs:
  test:
    runs-on: ubuntu-latest  # Используется Ubuntu, но можно изменить на windows-latest или macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Используется последняя версия для лучшей совместимости

      - name: Set up Python
        uses: actions/setup-python@v4  # Обновлена до последней версии
        with:
          python-version: '3.12.8'  # Укажите нужную версию Python

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Обновляем pip
          pip install -r requirements.txt  # Устанавливаем зависимости из requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Запуск тестов с ограничением на 1 ошибку
